### ISSUE TITLE
Link to manual is not obvious

### ISSUE THREAD

**Issue by tseemann** [andersen-lab/ivar#11]
For quite a while i thought this tool had no documentation.

But then I realised the word `Manual` in the README.md was not a subheading but a link to a wonderful set of detailed information!

Would it be possible to make this more prominent?
Maybe a sentence under the word "Manual" saying where all the docs are?

**Comment by gkarthik** [comment]
Added line under Manual :)

**Comment by tseemann** [comment]
Thank you
https://github.com/andersen-lab/ivar/issues/12
