### ISSUE TITLE
ivar trim drops deletions directly adjacent to trimmed primer sequence

### ISSUE THREAD

**Issue by wm75** [andersen-lab/ivar#120]
**Describe the bug**
With a deletion directly following a primer binding site ivar trim soft-clips the primer sequence correctly, but then "fills" the deletion by shifting the primer sequence into it.
This can be seen in the following screenshot of an ARTICv3 amplified sample with the S:YY144Y deletion, which is immediately 3' of 73_LEFT.

![Screenshot from 2022-03-07 12-47-13](https://user-images.githubusercontent.com/4742081/157029484-0350b6e1-a6b6-44c2-b9de-f6251a1ef741.png)

**Expected behavior**
I would expect ivar trim to keep the deletion and the soft-clipped bases in place.

**Additional context**
I'm seeing this behavior with ivar trim v1.3.1 so not sure whether this is related to https://github.com/andersen-lab/ivar/issues/36 or not.

**Comment by cmaceves** [comment]
could you please provide example data? @wm75

**Comment by wm75** [comment]
Sure, here's a minimal one.
[del_reads_before_and_after.zip](https://github.com/andersen-lab/ivar/files/8257716/del_reads_before_and_after.zip)

The full datasets these are taken from are available at:
- https://usegalaxy.eu/datasets/11ac94870d0bb33acb45394a35c6434d/display?to_ext=data&hdca_id=a91f2345202eaa76&element_identifier=SRR13402847 (before trimming)
- https://usegalaxy.eu/datasets/11ac94870d0bb33aaddf28af1c7ce296/display?to_ext=data&hdca_id=b32dbd194dbe0c97&element_identifier=SRR13402847 (after trimming)

**Comment by wm75** [comment]
btw, ivar trim was run with:
`ivar trim -i sorted.bam -b bed.bed -f amplicon_info.tsv -x 0 -e -m 1 -q 0 -p trimmed`

**Comment by cmaceves** [comment]
this issues is not due to ivar specifically, but the nature of how deletions are assigned. deletions cannot occur at the beginning of reads. samtools mpileup shows the deletion of the reference at these positions.
<img width="1440" alt="Screen Shot 2022-03-28 at 8 26 22 AM" src="https://user-images.githubusercontent.com/44014693/160435171-b582686e-f9a6-41fa-b335-948f747b90a0.png">

**Comment by wm75** [comment]
I don't quite understand how you produced that output, nor why you're saying at the beginning of a read (because it's only soft-clipped.

When I look at the demo files I provided with `samtools view`, then I'm getting the following:
```
> samtools view before_trimming.bam | cut -f 1-7
SRR13402847.97614	99	NC_045512.2	21974	60	17M3D233M	=
SRR13402847.116121	163	NC_045512.2	21974	60	17M3D233M	=
SRR13402847.24767	99	NC_045512.2	21979	60	12M3D239M	=
SRR13402847.112635	163	NC_045512.2	21982	60	9M3D56M	=
SRR13402847.112635	83	NC_045512.2	21982	60	9M3D56M	=
SRR13402847.24767	147	NC_045512.2	22031	60	251M	=
SRR13402847.97614	147	NC_045512.2	22031	60	251M	=
SRR13402847.116121	83	NC_045512.2	22048	60	250M	=
```
and after trimming:
```
> samtools view before_trimming.bam | cut -f 1-7
SRR13402847.97614	99	NC_045512.2	21994	60	17S233M	=
SRR13402847.116121	163	NC_045512.2	21994	60	17S233M	=
SRR13402847.24767	99	NC_045512.2	21994	60	12S239M	=
SRR13402847.112635	163	NC_045512.2	21994	60	9S56M	=
SRR13402847.112635	83	NC_045512.2	21994	60	9S56M	=
SRR13402847.24767	147	NC_045512.2	22031	60	251M	=
SRR13402847.97614	147	NC_045512.2	22031	60	251M	=
SRR13402847.116121	83	NC_045512.2	22048	60	250M	=
```
There's no trace of a deletion left in there, and in agreement with this when I run `samtools mpileup`:
```
> samtools mpileup -r NC_045512.2:21980-22000 -d 0 -B -Q 0 --ref NC_045512.2.fasta before_trimming.bam
[mpileup] 1 samples in 1 input files
[mpileup] Max depth set to maximum value (2147483647)
NC_045512.2	21980	T	3	...	FFB
NC_045512.2	21981	T	3	...	FFB
NC_045512.2	21982	T	5	...^].^],	FFBh!
NC_045512.2	21983	T	5	....,	FFBi!
NC_045512.2	21984	T	5	....,	FFFi!
NC_045512.2	21985	G	5	....,	CDDi!
NC_045512.2	21986	G	5	....,	GGDi!
NC_045512.2	21987	G	5	....,	GGAj!
NC_045512.2	21988	T	5	....,	EG2j!
NC_045512.2	21989	G	5	....,	EGAj!
NC_045512.2	21990	T	5	.-3TTA.-3TTA.-3TTA.-3TTA,-3tta	FGDj!
NC_045512.2	21991	T	5	*****	GGGi!
NC_045512.2	21992	T	5	*****	GGGi!
NC_045512.2	21993	A	5	*****	GGGi!
NC_045512.2	21994	T	5	....,	GGGi!
NC_045512.2	21995	T	5	....,	GGGm!
NC_045512.2	21996	A	5	....,	GGGm!
NC_045512.2	21997	C	5	....,	GGGm!
NC_045512.2	21998	C	5	....,	GGFn!
NC_045512.2	21999	A	5	....,	HHGn!
NC_045512.2	22000	C	5	....,	HHGm!
```
turn into:
```
> samtools mpileup -r NC_045512.2:21980-22000 -d 0 -B -Q 0 --ref NC_045512.2.fasta after_trimming.bam
[mpileup] 1 samples in 1 input files
[mpileup] Max depth set to maximum value (2147483647)
NC_045512.2	21994	T	5	^].^].^].^].^],	GGGBH
NC_045512.2	21995	T	5	....,	GGGFH
NC_045512.2	21996	A	5	....,	GGGFH
NC_045512.2	21997	C	5	....,	GGGGG
NC_045512.2	21998	C	5	....,	GGFGH
NC_045512.2	21999	A	5	....,	HHGGH
NC_045512.2	22000	C	5	....,	HHGGG
```
So I think this should be reopened.

**Comment by wm75** [comment]
... and from a very superficial look at the primer trimming code it looks as if
https://github.com/andersen-lab/ivar/blob/432b078581b30c299136700aad324aa01bf0a311/src/trim_primer_quality.cpp#L228-L230 is the issue? Not sure why this is done.

**Comment by cmaceves** [comment]
hi, sorry for the delay! if you could test again that would be helpful, *should* be fixed this time around @wm75 
<img width="976" alt="Screen Shot 2022-04-19 at 10 54 47 AM" src="https://user-images.githubusercontent.com/44014693/164065962-338cdd66-ab9e-4585-b9dc-87d84ee0443d.png">
.
