### ISSUE TITLE
Please update release

### ISSUE THREAD

**Issue by fizwit** [andersen-lab/ivar#133]
The current release is over a year old. To promote reproducible science, could you please update the release. We require tagged releases when building scientific software.  Pulling from the master is not reproducible.

Thank you for making your software available.

**Comment by cmaceves** [comment]
We're working on a few fixes, and then we'll generate a new release. Thank you for your patience!

**Comment by khyox** [comment]
We are also looking forward to a new release tag with all the updates and fixes since v1.3.1 was released in February 2021. Thank you so much for your work on iVar!
