### ISSUE TITLE
build from source fails with GCC >= 10

### ISSUE THREAD

**Issue by fizwit** [andersen-lab/ivar#134]
**Compile Error**
Pointer retuned from a mismatch allocation function. Error is enabled with GCC 10 or greater with  [-Werror=mismatched-new-delete]
Memory allocated with new is being "freed" with free().  Memory allocated with <new()> should be "freed" with <delete()>

**Steps to reproduce the behavior:**
Use GCC 10 or greater
git clone
cd ivar
./autogen.sh
./configure
make
```
ivar.cpp:502:11: error: ‘void free(void*)’ called on pointer returned from a mismatched allocation function [-Werror=mismatched-new-delete]
  502 |       free(files);
      |       ~~~~^~~~~~~
```

**Expected behavior**
Should build without compile errors

**Platform**
 - OS: Ubuntu 18.04
 - GCC 11.2.0

**Comment by cmaceves** [comment]
addressed in PR #136
