### ISSUE TITLE
slow performance of ivar 1.3.2 

### ISSUE THREAD

**Issue by pdp10** [andersen-lab/ivar#154]
**Is your feature request related to a problem? Please describe.**
In our pipeline, ivar was pinned to 1.3 (conda) and therefore we started using 1.3.2 as soon as this has been released. We noticed a significant slow down in performance (about 20 times slower). Pinning the version to 1.3.1 fixed our issue.

**Describe the solution you'd like**
`1.3.2` should not be as slow as it seems to be

**Describe alternatives you've considered**
We haven't had time to inspect the source code, but wondered whether there are specific reasons why the code has slowed us so much.

**Additional context**
This is how we executed ivar:
`ivar trim -e -i 3e5abbe9-34cc-4425-b17c-46aac223aa0a.mapped.bam -b SARS-CoV-2.scheme.bed -m 30 -q 20 -p ivar.out`
It will take us some time to get the full log.

**Comment by cmaceves** [comment]
hi! we actually are aware of this issue. sorry for any inconvenience, and we're looking to push a quick bump next week to fix this, and the issue has been documented in issue #147
