### ISSUE TITLE
ivar trim -f option incompatible with new piping functionality

### ISSUE THREAD

**Issue by wm75** [andersen-lab/ivar#157]
With v1.4 ivar trim can write SAM to stdout, but when the -f option is in use the amplicon interval tree will still print itself to stdout, too
https://github.com/andersen-lab/ivar/blob/98c2394639141a21c276f6c2e840c65fa1f6960c/src/interval_tree.cpp#L76-L82
, making those two functionalities incompatible for the moment.

**Comment by cmaceves** [comment]
thanks for brining this to my attention, we'll try and get it sorted out before it launches on bioconda!

**Comment by cmaceves** [comment]
Yeah I just realized that... It'll have to be on our next version bump.
