### ISSUE TITLE
clarification of ivar trim -e option

### ISSUE THREAD

**Issue by sgsutcliffe** [andersen-lab/ivar#163]
When reads are removed for an absence of primer (`ivar trim -e`), does this consider paired-reads? 

I ask because I'm using Nextera library prep kits which might lead to one read of a read-pair not containing a primer. Thanks!

**Comment by cmaceves** [comment]
hi! so when using it -e parameter, ```ivar trim``` will include reads that don't contain primer overlap. if you don't use the -e parameter, in the case of paired-end reads only the read that doesn't overlap with a primer will be removed!
