### ISSUE TITLE
iVar variants weird output 

### ISSUE THREAD

**Issue by sejmodha** [andersen-lab/ivar#164]
Hi There,

I am using iVar for variant calling on DNA virus genomes and I have noted that in some cases, iVar produces a gvcf-like output whereby most positions of the genome(s) are marked as variants. However, it is not a complete gvcf either as not all positions of the genome are listed in the output file. Is it expected behaviour or a bug? What would be the best solution to fix this weird output and only retain true variants?

I am using `ivar variants` to call variants and the output TSV is converted to VCF file using the [ivar_variants_to_vcf.py](https://raw.githubusercontent.com/nf-core/viralrecon/master/bin/ivar_variants_to_vcf.py) script.

```
VIRUS	23763	.	a	A	.	PASS	.	GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ	1:0:0:0:485:290:43:1
VIRUS	23764	.	g	G	.	PASS	.	GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ	1:0:0:0:485:290:43:1
VIRUS	23765	.	a	A	.	PASS	.	GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ	1:0:0:0:485:290:43:1
VIRUS	23766	.	a	A	.	PASS	.	GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ	1:0:0:0:1204:1184:41:1
VIRUS	23767	.	c	C	.	PASS	.	GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ	1:0:0:0:1204:1184:41:1
VIRUS	23768	.	a	A	.	PASS	.	GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ	1:0:0:0:1204:1184:41:1
VIRUS	23769	.	c	C	.	PASS	.	GT:REF_DP:REF_RV:REF_QUAL:ALT_DP:ALT_RV:ALT_QUAL:ALT_FREQ	1:0:0:0:320:207:41:1
```

Thanks
Sej

**Comment by cmaceves** [comment]
hi! would you mind sending me a over a snippet of your bam file and the exact command used?

**Comment by Moslemecoh** [comment]
I have called the variant using iVar. The command is given below:
 samtools mpileup -aa -A -d 600000 -B -Q 0 -r "$Ref" "$bamfile" | ivar variants -p "${base_name}_vari" -q 20 -t 0.03 -r "$Ref" -g "$gff"
But the output in the tsv file did not show anything. How can I solve this problem?

**Comment by cmaceves** [comment]
is there any way you can either send me (a) a link to a drive containing the bam and reference or (b) a smaller portion of the bam file and reference where you see this issue? you can email it over to caceves@scripps.edu

**Comment by Moslemecoh** [comment]
> is there any way you can either send me (a) a link to a drive containing the bam and reference or (b) a smaller portion of the bam file and reference where you see this issue? you can email it over to [caceves@scripps.edu](mailto:caceves@scripps.edu)

Hi Chrissy Aceves,
I have solved the problem and got the result of variant. Thank you.

**Comment by cmaceves** [comment]
awesome, thanks for posting. will close the issue!
