### ISSUE TITLE
missing #include <algorithm>

### ISSUE THREAD

**Issue by jenniferliddle** [andersen-lab/ivar#19]
I had to add
`#include <algorithm>`
to primer_bed.h
in order to avoid the compilation error:
‘all_of’ is not a member of ‘std’

**Comment by gkarthik** [comment]
Could you please add the version of `gcc` you're using. I think this should be included in `-std=c++11`. Thanks!

**Comment by jenniferliddle** [comment]
I've tried with both 8.1.0 and 9.1.0 versions of gcc. 
I'm using the supplied configure script and can confirm the makefile includes -std=c++11
