### ISSUE TITLE
Print out minimum depth

### ISSUE THREAD

**Issue by josephhughes** [andersen-lab/ivar#21]
When running ivar consensus with the minimum depth option -m and the threshold (-t), the output to stdout does not provide the minimum  depth.

```
samtools mpileup -B -A -d 1000000 -Q 0 input.bam | ivar consensus -p output_consensus -n N -t 0.6 -m 10
[mpileup] 1 samples in 1 input files
Minimum Quality: 20
Threshold: 0.6
Minimum depth: 

Regions with depth less than minimum depth covered by: N
```

The program is filtering based on depth so is working properly but first thought that it was not filtering based on depth due to the lack of info on stdout.

**Comment by gkarthik** [comment]
Thank you for raising the issue. This was fixed by 56e5c865fae27e656f7d59c932d7ec0c895199e1. Planning a release within the next few days.
