### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by jenniferliddle** [andersen-lab/ivar#25]
I'm getting a lot of compilation warnings (with g++ 8.1.0) mostly concerning comparison of signed with unsigned variables, along with unused variables.

If I were to add -Werror to CXXFLAGS and fix the warnings, would you consider a pull request?

**Comment by gkarthik** [comment]
Sure, that would be great! I've been meaning to look into those. In most cases harmless but I would like a clean log :)

**Comment by gkarthik** [comment]
@jenniferliddle in case you're still interested, I just created a release and fixed a couple of things on the master branch. A pull request on some of these issues would be appreciated :).

**Comment by jenniferliddle** [comment]
Done!
(I was wondering why you only seemed to work at night, before I realised the obvious, that we're in different time zones)

**Comment by gkarthik** [comment]
Merged request https://github.com/andersen-lab/ivar/pull/26. Thank you! 
Timezones can be annoying :)
