### ISSUE TITLE
ivar trim to stdout ?

### ISSUE THREAD

**Issue by tseemann** [andersen-lab/ivar#27]
currently need to do `ivar trim -i in.bam -p out` to get `out.bam`
it seems to only write 1 file, the bam?
can you support stdout please so I can pipe it to the next stage?

eg. if no `-p` do this?
```
ivar trim -i in.bam | samtools sort -n | samtools fastq > reads.fq
```

**Comment by EdoardoGiussani** [comment]
Is there any news on this feature? It would be great to reduce the amount of intermediate files and disk space.

**Comment by Rohit-Satyam** [comment]
Did it get implemented?? I agree with the suggestion.

**Comment by cmaceves** [comment]
Hi, this is a feature currently under development! @Rohit-Satyam
