### ISSUE TITLE
Isolate quality trimming

### ISSUE THREAD

**Issue by gkarthik** [andersen-lab/ivar#35]
For item 1 in https://github.com/broadinstitute/viral-pipelines/issues/28

**Comment by dpark01** [comment]
I think the cleanest approach (from a UI perspective) would simply be to make `-b` an optional parameter for `ivar trim`, and leave all else the same.

**Comment by tseemann** [comment]
This seems dangerous to me. 
Forget an option and it doesn't do what the tool is actually mostly designed for?

**Comment by dpark01** [comment]
This command actually does two things: one was previously required and one was previously optional, and now they are both optional. But maybe that's an argument for splitting them into two commands? (trimprimers, trimquality). Does the new samtools command do everything `-b` does in ivar trim now?

**Comment by gkarthik** [comment]
@dpark01 I think the new samtools command in development is intended to do what ivar trim does with the primer trimming. Not sure if they want to port more of the functionality. 

@tseemann I add a line to the log stating that without the BED file all the reads regardless of primers were written to file.
