### ISSUE TITLE
Corrupt primer-trimmed bam file

### ISSUE THREAD

**Issue by kaganr** [andersen-lab/ivar#38]
**Describe the bug**
ivar trim creates a corrupt primer-trimmed bam file:

> samtools view 178Ct21-C74045848_S178.primertrim.sorted.bam
[E::sam_format1] Corrupted aux data for read M02568:512:000000000-J52NT:1:1103:25289:20956
samtools view: writing to standard output failed: Invalid argument

**To Reproduce**
Command to generate the bam file:
ivar trim -i $sampleID.sorted.bam -b /seq/Development/Projects/covid/References/ARTIC-1k-primer.bed -p $sampleID.primertrim
samtools sort -@ 8 $sampleID.primertrim.bam -o $sampleID.primertrim.sorted.bam

**Expected behavior**
samtools view should behave normally

**Screenshots**

**Desktop (please complete the following information):**
 Redhat linux 7
> uname -a
Linux sjlsd0018.us.qdx.com 3.10.0-1062.7.1.el7.x86_64 #1 SMP Wed Nov 13 08:44:42 EST 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gkarthik** [comment]
ivar stores the primer indice in the auxiliary tag for downsteam analysis. Seems like for some reason it’s storing an unintended type. Which version of ivar are you using?

**Comment by kaganr** [comment]
This was using ivar version 1.1

Ron M. Kagan, Ph.D.
Director of Bioinformatics, Molecular Infectious Diseases
Quest Diagnostics | Action from Insight | 33608 Ortega Highway | San Juan Capistrano, CA 92675 USA | phone 949.728.1882 | mobile 949.275.6138 | fax: 949.728.7180 | Ron.M.Kagan@questdiagnostics.com<mailto:Ron.M.Kagan@questdiagnostics.com> | QuestDiagnostics.com<http://questdiagnostics.com/>

**Comment by gkarthik** [comment]
Could you please upgrade to `v1.2` or `v1.2.1` and see if this error persists? Thank you.

**Comment by kaganr** [comment]
Sure, we will give it a try!

**Comment by kaganr** [comment]
We tested ivar 1.2.1 and still got the same error from samtools when trying to view the bam file.

**Comment by gkarthik** [comment]
1. Any chance you can upload a highly downsampled untrimmed BAM file or just the reads `M02568:512:000000000-J52NT:1:1103:25289:20956`? 
2. To clarify is this the artic V3 protocol?

**Comment by kaganr** [comment]
Clarification: let me get back to you on the test – my colleague actually tested something else with v1.2.1 unrelated to this (will open a separate issue for that), not the test you requested.  Let me test it right now and will update you.  Yes, ARTIC V3 protocol.  If still the same, where to upload the bam file?

**Comment by gkarthik** [comment]
You can upload the file here. Or email it to me at gkarthik@scripps.edu if you want to keep it off GH. Thanks!

**Comment by kaganr** [comment]
Turns out that ivar 1.2.1 actually fixes the issue – tested it on 2 separate bam files.  Did not get an error when viewing the primer-trimmed file with samtools.  Then retested with ivar 1.1 and got the error again.  Thanks!

$IVAR trim -i 171Ct26-C74031299_S171.sorted.bam -b $BED -p 171Ct26-C74031299_S171.primertrimV3
samtools sort -@ 8 -o 171Ct26-C74031299_S171.primertrimV3.sorted.bam 171Ct26-C74031299_S171.primertrimV3.bam
samtools view -c 171Ct26-C74031299_S171.primertrimV3.sorted.bam | more
44614

**Comment by gkarthik** [comment]
I had the primer indice set to an unsigned 8 bit integer which I changed to an unsigned 16 bit integer in the new version. Glad it worked! Thank you for testing it.
