### ISSUE TITLE
[E::bam_read1] CIGAR and query sequence lengths differ

### ISSUE THREAD

**Issue by drpatelh** [andersen-lab/ivar#42]
**Describe the bug**

`samtools sort` is failing on output of `ivar trim` with v1.2.1 of `iVar` on Bioconda. This wasnt an issue with v1.2. Apparently, Conda will resolve the environment to contain v1.2.1 even though I had explicitly specified [`v1.2`](https://github.com/nf-core/viralrecon/blob/760d2cd6ac47fb6cf0b38a8da9da0d8a53d4e6eb/environment.yml#L32). Since this environment is automatically built within a Docker container whenever we merge to `dev`/`master` it took a bit of work figuring out why our pipeline CI tests were failing 😅 

```bash
Caused by:
  Process `IVAR_TRIM (SAMPLE3_SE)` terminated with an error exit status (1)

Command executed:

  samtools view -b -F 4 SAMPLE3_SE.sorted.bam > SAMPLE3_SE.mapped.bam
  samtools index SAMPLE3_SE.mapped.bam

  ivar trim \
      -i SAMPLE3_SE.mapped.bam \
      -e \
      -b nCoV-2019.artic.V1.bed \
      -p SAMPLE3_SE.trim > SAMPLE3_SE.trim.ivar.log

  samtools sort -@ 2 -o SAMPLE3_SE.trim.sorted.bam -T SAMPLE3_SE.trim SAMPLE3_SE.trim.bam
  samtools index SAMPLE3_SE.trim.sorted.bam
  samtools flagstat SAMPLE3_SE.trim.sorted.bam > SAMPLE3_SE.trim.sorted.bam.flagstat
  samtools idxstats SAMPLE3_SE.trim.sorted.bam > SAMPLE3_SE.trim.sorted.bam.idxstats
  samtools stats SAMPLE3_SE.trim.sorted.bam > SAMPLE3_SE.trim.sorted.bam.stats

Command exit status:
  1

Command output:
  (empty)

Command error:
  [E::bam_read1] CIGAR and query sequence lengths differ for M03352:174:000000000-J3R29:1:1119:12450:3784
  samtools sort: truncated file. Aborting
```

The CIGAR string for that read is indeed astronomically large, and definitely not a product of long-read sequencing!

```bash
> samtools view SAMPLE3_SE.trim.bam | grep "M03352:174:000000000-J3R29:1:1119:12450:3784"
M03352:174:000000000-J3R29:1:1119:12450:3784    16      NC_045512.2     4967    22      48S173246631M   *       0       0       CTTCTTTCTTTGAGAGAAGTGAGGACTTGTTCTTACCTTCTTTTCCA      GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCCCCC AS:i:54 XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:27 YT:Z:UU XA:i:32
```

**To Reproduce**

All files required to reproduce the error are in the attached tar archive. Please see `command.sh` for the commands used.
[ivar_bug.tar.gz](https://github.com/andersen-lab/ivar/files/4519020/ivar_bug.tar.gz)

**Comment by tseemann** [comment]
Are these Illumina SE, Illumina PE, or Nanopore ONT reads?

**Comment by gkarthik** [comment]
Thank you for pointing this out! I isolated the issue: The entire read `M03352:174:000000000-J3R29:1:1119:12450:3784` seems to span only the primer region of `nCoV-2019_17_LEFT (4939 - 4965)`,  with some sequence before it being soft clipped. 

Patching the issue now. Will update once its fixed.

<img width="1245" alt="Screen Shot 2020-04-22 at 4 27 53 PM" src="https://user-images.githubusercontent.com/798263/80043335-408b3280-84b6-11ea-8f92-7901588f7c94.png">

PS: Fantastic bug report. Made debugging this quite straight forward!

**Comment by drpatelh** [comment]
Amazing! Thanks @gkarthik 

@tseemann Thanks for pointing that out :+1:  The reads actually originate from MiSeq PE ARTIC V1 amplicon data but for the purposes of testing SE data I have just used R1 as you can see in this [samplesheet](https://github.com/nf-core/test-datasets/blob/viralrecon/samplesheet/samplesheet_test_amplicon.csv).

**Comment by tseemann** [comment]
It it is merged/stitched ILL reads then `-e` should maybe not be used?

**Comment by drpatelh** [comment]
Ah, for PE data the reads are not currently overlapped to get a single representative read for the fragment. Sorry, is that what you meant? They are mapped directly after quality and adapter trimming.

I got the commands for `ivar consensus` for Illumina data from [here](https://github.com/CDCgov/SARS-CoV-2_Sequencing/tree/master/protocols/BFX-UT_ARTIC_Illumina). Thanks @tseemann 😎 I saw that you werent using `-e` in the `ivar trim` step so added an [optional parameter](https://github.com/nf-core/viralrecon/blob/e23be8f28063010ff27ab7a4644987ad6439488e/main.nf#L56) to the pipeline to switch it off. Maybe @saramonzon can provide a more detailed explanation as to why we are using it in this way.

Suggestions/feedback/contributions more than welcome 😃

**Comment by drpatelh** [comment]
PS: Last order of business for now is to try to get [`iVar`](https://github.com/ewels/MultiQC/pull/1159#discussion_r413026783), `VarScan 2` and `Kraken2` modules added to MultiQC and we should be good to go for an initial release.

**Comment by apeltzer** [comment]
Kraken2 is much more complicated to do, not really having an idea atm but will nevertheless try - see the https://github.com/ewels/MultiQC/pull/1161 for some idea(s). VarScan2 and iVar modules have been written and are ready to go once Phil is fine with them 👍

**Comment by gkarthik** [comment]
@drpatelh I just pushed a new [release](https://github.com/andersen-lab/ivar/releases/tag/v1.2.2) that fixes this. I used it on your test data and it works fine. Please let me know if this works!

@tseemann Even if reads are merged, reads could still start in between primers so `-e` option might still be required?

**Comment by drpatelh** [comment]
Gorgeous! Thanks for doing this so quickly @gkarthik 

Updated the environment and tests are purrrrring again :)

![image](https://user-images.githubusercontent.com/23529759/80199589-6da42600-8619-11ea-8602-711bba3363e4.png)

**Comment by paulstretenowich** [comment]
Hi @gkarthik, I was having the same issue as @drpatelh with version 1.2.1 so I switched to version 1.2.2 and now I have another issue: No reads are having any primer while with version 1.2.1 primers were found within reads and reported.
Here is an example of my issue:
```
ivar version 1.2.1:
ivar trim -i L00240979.sorted.bam -b PGD99s.ampInfo.bed -p L00240979.sorted.ivar_primerTrim -m 30 -q 20 -s 4
Found 686 primers in BED file

Number of references in file: 1
MN908947.3
Using Region: MN908947.3

Found 3163806 mapped reads
Found 0 unmapped reads
Sorted By Coordinate
-------
Processed 10% reads ...
Processed 20% reads ...
Processed 30% reads ...
Processed 40% reads ...
Processed 50% reads ...
Processed 60% reads ...
Processed 70% reads ...
Processed 80% reads ...
Processed 90% reads ...
Processed 100% reads ...

-------
Results:
Primer Name           Read Count
PGD99s_MN908947.3_1L     88
PGD99s_MN908947.3_1R     63
PGD99s_MN908947.3_2L    9149
PGD99s_MN908947.3_2R    13
PGD99s_MN908947.3_3L    3841
PGD99s_MN908947.3_3R    12
PGD99s_MN908947.3_4L    4148

ivar version 1.2.2:
ivar trim -i L00240979.sorted.bam -b PGD99s.ampInfo.bed -p L00240979.sorted.ivar_primerTrim -m 30 -q 20 -s 4
Found 686 primers in BED file

Number of references in file: 1
MN908947.3
Using Region: MN908947.3

Found 3163806 mapped reads
Found 0 unmapped reads
Sorted By Coordinate
-------
Processed 10% reads ...
Processed 20% reads ...
Processed 30% reads ...
Processed 40% reads ...
Processed 50% reads ...
Processed 60% reads ...
Processed 70% reads ...
Processed 80% reads ...
Processed 90% reads ...
Processed 100% reads ...

-------
Results:
Primer Name           Read Count
PGD99s_MN908947.3_1L     0
PGD99s_MN908947.3_1R     0
PGD99s_MN908947.3_2L    0
PGD99s_MN908947.3_2R    0
PGD99s_MN908947.3_3L    0
PGD99s_MN908947.3_3R    0
PGD99s_MN908947.3_4L    0
```

**Comment by gkarthik** [comment]
Hey @paulstretenowich , the one change I made was taking the primer strand into account. So the +ve strand gets trimmed from 5' end and -ve strand from 3' end. If a read is unpaired then the primers are trimmed from both ends else if its paired then for a forward read the +ve strand primers are trimmed and if its reverse then the -ve strand primers. 

Do you think this might have made a difference to your data?

**Comment by paulstretenowich** [comment]
Hi @gkarthik, in my primer.bed I don't a have the strand info. Is it because of that missing info?

Thanks,
Paul

**Comment by gkarthik** [comment]
Yes, I think that might be the issue. I should include include a check on the number of columns to account for this. Thank you for pointing this out! Please let me know if that fixes the issue

**Comment by paulstretenowich** [comment]
Will you do a new release for that? I'll try as soon as you point me to the new version and be back to you.

Thanks,
Paul

**Comment by gkarthik** [comment]
Could you please add the strand and check if `v1.2.2` works? I'll include a check to make sure strand is present with the next release but I think with NextEra, strand information will be important, otherwise a lot of bases get trimmed off in the primer positions.

**Comment by paulstretenowich** [comment]
I'm using ivar on MGI/Parangon CleanPlex data and I have the bed file of the amplicons and the bed file of the inserts so I calculate the primers by doing the difference between the inserts and the amplicons so I end up with 2 primer intervals for a given amplicon/insert. Does it make sense to deduce the strand from primers, like primer left strand + and primer left strand - ?

**Comment by paulstretenowich** [comment]
Doing that I still have 96.48% (3052585) of reads started outside of primer regions which is very high because with version 1.2.1 I had 11.35% (358985) of reads started outside of primer regions.

**Comment by gkarthik** [comment]
I haven't looked at CleanPlex data so I'm not sure if strand has to be taken into account for such data. 

I just pushed two commits to the `master` branch that will ignore strand if its not specified. Could you please compile the master branch and check if the trimming works with a BED file without the strand specified? If it solves it, I'll create a new release. Thanks!

**Comment by paulstretenowich** [comment]
It's working without strand thanks!

**Comment by gkarthik** [comment]
Awesome! I'll include this in the next release. A few more things to add and I'll make a release over the weekend.

**Comment by paulstretenowich** [comment]
Hi @gkarthik, do you plan to integrate a way to paralyze ivar to speed it up?

**Comment by gkarthik** [comment]
Release coming soon! 
Multithreading has been on my mind but it will take sometime to get that going given my schedule. Is there a particular step that you find taking too much time?

**Comment by paulstretenowich** [comment]
Great!
The consensus step is a bit long but is it because of samtools or ivar? Other than that it's pretty fast, I was just asking as I'm using HPCs I can use many threads to speed up even more.

**Comment by tseemann** [comment]
mpileup is the bottleneck. 
you can parallelize over regions 
`-r, --region REG        region in which pileup is generated`
but you still need to paste together to feed into ivar.
`parallel -k` will ensure the stdout is in the region ordfer.
