### ISSUE TITLE
ivar trim doesn't fail when providing an improper BED file

### ISSUE THREAD

**Issue by jackkamm** [andersen-lab/ivar#46]
**Describe the bug**
Previously in version 1.2, if an improper BED file was provided, then `ivar trim` would fail. However in 1.2.2, if an improper BED file is provided, then `ivar trim` won't fail, it will simply skip trimming, but still output a bam file, as if no `-b` option had been provided, potentially causing the error to go unnoticed. Related to https://github.com/andersen-lab/ivar/issues/35

**To Reproduce**
1. Download the BED file from https://github.com/artic-network/artic-ncov2019/blob/master/primer_schemes/nCoV-2019/V3/nCoV-2019.bed. The 5th column is not an integer so `ivar trim` will consider it invalid.
2. Run `ivar trim` using this bed file. `ivar trim` will complain about the BED file format:
```
iVar uses the standard 6 column BED format as defined here - https://genome.ucsc.edu/FAQ/FAQformat.html#format1.
It requires the following columns delimited by a tab: chrom, chromStart, chromEnd, name, score, strand
```
But then proceed anyways, resulting in no reads being trimmed:
```
Trimmed primers from 0% (0) of reads.
0.73% (10132) of reads were quality trimmed below the minimum length of 30 bp and were not writen to file.
99.27% (1376097) of reads started outside of primer regions. Since the -e flag was given, these reads were written to file.
```

**Comment by gkarthik** [comment]
Thank you for pointing this out! Ideal behavior for a wrong BED file would be no output. Will fix this in the next release.
