### ISSUE TITLE
Document altered primer trimming rules for PE data in v1.2.2

### ISSUE THREAD

**Issue by wm75** [andersen-lab/ivar#50]
@gkarthik after noticing drastic changes in the number of trimmed primer seqs between ivar 1.2.1 and 1.2.2, I came across your comment in https://github.com/andersen-lab/ivar/issues/42#issuecomment-622534652 stating that version 1.2.2 is now taking primer strand information into account.

Given how big the impact of this change seems to be, I would say it deserves some proper documentation. At least it should be highlighted in the release notes.

Also, just to make sure I understand the motivation behind this change: the idea is that you want to trim the primers from reads derived from the corresponding amplicon, but not from reads derived from overlapping (second-pool) amplicons that happen to end at those primer binding sites?
So a substantially reduced number of trimmed primer sequences upon a version upgrade (a bit alarming at first glance) should actually be considered an improvement?

**Comment by gkarthik** [comment]
Yes, your reasoning as to why I used the strand information is correct. This becomes very essential especially if there is a NextEra step. 

Will get around to documenting this soon hopefully!
