### ISSUE TITLE
is ivar getmasked broken at the current version?

### ISSUE THREAD

**Issue by wm75** [andersen-lab/ivar#52]
Hi,
I just tested `ivar getmasked` at versions 1.2.2 and 1.2.1 and the tool seems completely broken!
Instead of reporting primer pairs, it simply lists primers with mismatches.

I checked against version 1.0.1 and that one works as expected. Seems something bad has happened to the tool in between?

Can you confirm that observation?

**Comment by gkarthik** [comment]
Hey, thank you for pointing this out. I'm not quite sure how this got through but I just fixed this on `master`.
