### ISSUE TITLE
Memory leaks in ivar trim

### ISSUE THREAD

**Issue by jenniferliddle** [andersen-lab/ivar#57]
**Describe the bug**
The 'trim' command has some memory leaks. Other commands may too, but I haven't checked those yet.

**To Reproduce**
I've been using 'sanitize' to check my changes by using:

`make -j 8 CFLAGS='-g -gdwarf-2 -Wall -Werror -fsanitize=address' LDFLAGS='-fsanitize=address'`

followed by 

`make -j 8 CFLAGS='-g -gdwarf-2 -Wall -Werror -fsanitize=address' LDFLAGS='-fsanitize=address' check`

This is showing a number of memory leaks, both in the unit tests and in ivar itself.
I'm using gcc 8.1.0

I'll try to put together a PR to address these...

**Comment by gkarthik** [comment]
This would be very helpful! Thank you. I've been using valgrind to profile memory and the couple of memory leaks have been on my radar for a while.

**Comment by jenniferliddle** [comment]
There is now a PR #58 to hopefully address this.

**Comment by gkarthik** [comment]
Merged #58
