### ISSUE TITLE
TOTAL_DP is inconsistent with -m parameter

### ISSUE THREAD

**Issue by jts** [andersen-lab/ivar#65]
**Describe the bug**

Occasionally variants are called where TOTAL_DP is less than the user-provided depth threshold (`-m`) (for example with `-m 10` we observe variants with `TOTAL_DP` as low as 3). It appears that ivar checks depth based on the raw mpileup output, prior to any filtering (for example by quality score `-q`). This may lead to low quality variant/consensus calls when most of the reads don't pass the quality filter.

**Expected behavior**

I would find it more intuitive, and possibly lead to better results, if the depth check was applied after any read filtering.

**Comment by gkarthik** [comment]
Thank you for pointing this out! When I added this filter, I remember thinking about this very issue but decided to go with the unfiltered depth to keep it simple. However, I agree with your point that using `filtered depth` will lead to better results.
