### ISSUE TITLE
ivar version is hardcoded to 1.0.0 in output BAM header

### ISSUE THREAD

**Issue by jts** [andersen-lab/ivar#67]
**Describe the bug**

When `ivar` writes a BAM file (like in `ivar trim`) the version number in the `@PG` tag is always 1.0.0:

https://github.com/andersen-lab/ivar/blob/f09c3067eb5dd9fea6f764ecfef65aed58665e8f/src/ivar.cpp#L195

**Expected behavior**

The version number should be the correct version, as defined here:

https://github.com/andersen-lab/ivar/blob/master/src/ivar.cpp#L19

**Comment by gkarthik** [comment]
Thank you for catching this!
