### ISSUE TITLE
Further clarification for setting up primers BED file

### ISSUE THREAD

**Issue by charlesfoster** [andersen-lab/ivar#77]
Hi,

Apologies for the very basic question, but I'd just like to clarify how the primer coordinates in the BED file for primer trimming should be set up to ensure the primer trimming is completed correctly. I'll use the ARTIC v3 primer scheme (used with `ivar` in their protocol) as an example: https://github.com/artic-network/primer-schemes/blob/master/nCoV-2019/V3/nCoV-2019.primer.bed

The "nCoV-2019_1_LEFT" primer is "ACCAACCAACTTTCGATCTCTTGT", and the start and end coordinates in the BED file are given as 30 and 54, respectively. However, if you search for the primer within the SARS-CoV-2 reference genome (MN908947.3), it matches positions 31 to 54, i.e. the start appears to be 1 base after the coordinate in the BED file. The same holds true for all other primers: they match from the BED start coordinate +1.

Is this the way that the primer BED file should be set up to be properly parsed by `ivar`? I just need to ensure that I set up the file correctly for the different amplicon scheme we're using.

Thanks!

**Comment by gkarthik** [comment]
Hello Charles,

`ivar` follows the standard BED format where the start position is 0 based and the end position is 1-based. 
http://genome.ucsc.edu/FAQ/FAQtracks#tracks1
The default BED file should work fine. Please let me know if it does. Thanks!

Best Regards,
Karthik

**Comment by charlesfoster** [comment]
Hi Karthik,

Thanks for the clarification - that makes a lot of sense now. The default BED file works, but (perhaps naively) it gives me results that are somewhat unexpected. I downloaded reads from the SRA that I know were amplified with the ARTIC v3 primers, and used the corresponding primer scheme bed file. `ivar` was run like follows:

`ivar trim -i analysis/test_results/mapping_output/test_sorted.bam -b bin/primers.bed -p analysis/test_results/variant_output/test_iTrimmed -m 30 -q 20 -s 4`

After trimming is complete, I get this output:

>Trimmed primers from 20.28% (144945) of reads.
3.42% (24424) of reads were quality trimmed below the minimum length of 30 bp and were not written to file.
77.19% (551599) of reads that started outside of primer regions were not written to file.

Trimming results in nearly 80% of the reads being thrown away, with the majority of these being because of reads starting outside of primer regions. The coverage is necessarily not great after that point. However, if I implement the `-e` flag of `ivar` to avoid throwing out the reads starting outside of the primer regions, the coverage etc. looks great.

Do you have a recommendation or not for implementing this `-e` flag with amplicon data since it's off by defaults? 

Thanks,
Charles

**Comment by gkarthik** [comment]
Hello Charles,

Glad to be of help! If there was a fragmentation step (NextEra) during library prep then the `-e` flag is recommended else there shouldn't be a need to use `-e` since all the reads will start and end at primer regions.

Best,
Karthik

**Comment by charlesfoster** [comment]
Perfect! That makes sense. Thanks for the fast reply.

Charles
