### ISSUE TITLE
Codon numbering

### ISSUE THREAD

**Issue by AKWB** [andersen-lab/ivar#78]
I am using IVar for SARS-CoV-2 analysis and it would be really helpful to get in the variants output not only the genomic coordinates, but also the number for the codon affected if there is a aminoacid exchange. Would it be possible to add this feature?

Best,
AKWB

**Comment by AlaaALatif** [comment]
Yea, that would be useful to add. Will explore adding it soon. Thank you! 

Al

**Comment by AKWB** [comment]
Hi,

sorry to bother...any updates on that feature? I don't know how complicated it is, but it would make my life extremly easier and would accelate our workflows pretty strong. Otherwise I will need to set up now a final workaround for me ;-/.

Best,
AKWB

**Comment by gkarthik** [comment]
Hello AKWB,

Thank you for your patience. It isn't very complicated but unfortunately we are tied up with other COVID19 things at the moment. We will probably be able to add this feature within the next 2 weeks or so. We will keep you updated. 

Best,
Karthik

**Comment by AKWB** [comment]
Same for us ;-). Super busy with COVID. 2 weeks is already pretty good!!! Then I wait. Thanks!!!!!!!

 
 

Gesendet: Mittwoch, 25. November 2020 um 19:33 Uhr
Von: "Karthik" <notifications@github.com>
An: "andersen-lab/ivar" <ivar@noreply.github.com>
Cc: "AKWB" <Anke.Wienecke@gmx.net>, "Author" <author@noreply.github.com>
Betreff: Re: [andersen-lab/ivar] Codon numbering (#78)


 

Hello AKWB,

Thank you for your patience. It isn't very complicated but unfortunately we are tied up with other COVID19 things at the moment. We will probably be able to add this feature within the next 2 weeks. We will keep you updated.

Best,
Karthik

**Comment by AKWB** [comment]
Hey Karthik,

any news on the codon numbering ;-)?

Greets,
Anke

**Comment by cmaceves** [comment]
addressed by PR #127
