### ISSUE TITLE
Deletion in SARS-CoV-2 added some  NNs

### ISSUE THREAD

**Issue by btaboada75** [andersen-lab/ivar#89]
**Describe the bug**
When there is a deletion followed by bases less than -m, instead of delete the bases ivar put N

**To Reproduce**
For example, the result of ivar variant is:
MN908947.3      685     A       -AAGTCATTT      216     177     24      893     0       20      4.13426 216     5.97804e-121    TRUE
MN908947.3      686     A       G       2       2       30      2       2       32      0.5     4       0.285714        FALSE
MN908947.3      688     G       -TCATTT 0       0       0       3       0       20      inf     0       1       FALSE
MN908947.3      689     T       -CATTTGA        1       1       32      2       0       20      2       1       1       FALSE
MN908947.3      691     A       -TTT    2       2       20      2       0       20      1       2       0.6     FALSE

As you can see there is a deletion of 9 nucleotides starting at  position 685, but the consensus sequence has three Ns:
ANNNG. I guess is becouse some position between 685 and 694 had values less than 3 that was the value used in -m option.

Te consensus results must be only AG in this part of the sequence.

Other thing is the deapth value of the reference, becouse if you see the vcf result obtaing by samtools and  bcftools call it has different values.

MN908947.3      685     .       A       .       285     .       DP=1727;ADF=39;ADR=177;AD=216;MQSB=0.430831;MQ0F=0;AN=2;DP4=39,177,0,0;MQ=39    GT:DP:SP:ADF:ADR:AD     0/0:216:0:39:177:216
MN908947.3      685     .       AAAGTCATTT      A       222     .       INDEL;IDV=901;IMF=0.518114;DP=1739;ADF=151,389;ADR=714,485;AD=865,874;VDB=0.024003;SGB=-0.693147;MQSB=1.79135e-26;MQ0F=0;ICB=1;HOB=0.5;AC=1;AN=2;DP4=151,714,389,485;MQ=35        GT:PL:DP:SP:ADF:ADR:AD  0/1:255,0,142:1739:255:151,389:714,485:865,874
MN908947.3      686     .       A       G       14.5547 .       DP=8;ADF=0,0;ADR=2,2;AD=2,2;VDB=0.02;SGB=-0.453602;RPB=0;MQB=1;BQB=0.5;MQ0F=0;ICB=1;HOB=0.5;AC=1;AN=2;DP4=0,2,0,2;MQ=42 GT:PL:DP:SP:ADF:ADR:AD  0/1:47,0,44:4:0:0,0:2,2:2,2
MN908947.3      687     .       A       .       84      .       DP=10;ADF=1;ADR=1;AD=2;MQSB=1;MQ0F=0;AN=2;DP4=1,1,0,0;MQ=31     GT:DP:SP:ADF:ADR:AD     0/0:2:0:1:1:2
MN908947.3      688     .       G       .       29.5864 .       DP=9;ADF=0;ADR=0;AD=0;MQ0F=0;AN=0;DP4=0,0,0,0;MQ=.      GT:DP:SP:ADF:ADR:AD     ./.:0:0:0:0:0
MN908947.3      689     .       T       .       62      .       DP=6;ADF=0;ADR=1;AD=1;MQ0F=0;AN=2;DP4=0,1,0,0;MQ=44     GT:DP:SP:ADF:ADR:AD     0/0:1:0:0:1:1
MN908947.3      690     .       C       .       88      .       DP=4;ADF=1;ADR=2;AD=3;MQSB=1;MQ0F=0;AN=2;DP4=1,2,0,0;MQ=27      GT:DP:SP:ADF:ADR:AD     0/0:3:0:1:2:3
MN908947.3      691     .       A       .       66      .       DP=3;ADF=0;ADR=2;AD=2;MQ0F=0;AN=2;DP4=0,2,0,0;MQ=30     GT:DP:SP:ADF:ADR:AD     0/0:2:0:0:2:2
MN908947.3      692     .       T       .       29.5864 .       DP=0;ADF=0;ADR=0;AD=0;MQ0F=0;AN=0;DP4=0,0,0,0;MQ=.      GT:DP:SP:ADF:ADR:AD     ./.:0:0:0:0:0
MN908947.3      693     .       T       .       62      .       DP=4;ADF=1;ADR=0;AD=1;MQ0F=0;AN=2;DP4=1,0,0,0;MQ=44     GT:DP:SP:ADF:ADR:AD     0/0:1:0:1:0:1
MN908947.3      694     .       T       .       84      .       DP=6;ADF=1;ADR=1;AD=2;MQSB=1;MQ0F=0;AN=2;DP4=1,1,0,0;MQ=44      GT:DP:SP:ADF:ADR:AD     0/0:2:0:1:1:2

Software used:
module load programs/samtools-1.9
module load programs/ivar-1.0
module load programs/bowtie2-2.3.4.3

Best regards,

Blanca Taboada

**Comment by gkarthik** [comment]
Resolved over email. Had to do with BAQ calculation when reference supplied to samtools mpileup for consensus calling.
