### ISSUE TITLE
iVar trim taking a long time/endless loop

### ISSUE THREAD

**Issue by ptskidmore** [andersen-lab/ivar#93]
Hello,

I have been experimenting with using iVar trim for primer sequences with a SARS-CoV-2 amplicon panel and am noticing it running for a long time (>2 hours) for a single sample before canceling the command. Up until now I have used Primerclip to handle trimming and samples such as these typically only take 2-3 minutes (samples typically end up with ~1 million reads and coverage ranging from 1,000 to 3,000). Is this expected behavior for iVar or am I using it incorrectly?

This is the command I have been using:
ivar trim -e -i {sample}.sorted.bam -b {primers.bed} -p {sample}.primertrim

With primer bed file looking like this:
![image](https://user-images.githubusercontent.com/9160742/112904978-93924000-909e-11eb-88ce-8e42e22a8702.png)

**Comment by demiglidden** [comment]
@ptskidmore Hi there! I was running into a similar issue trying to run this command on my mac. The command consistently stalled here:
`(snakemake) demi 12:34 Wed Jun 02 : ivar trim -b articprimers_v3.fa -p trimmed_sample1_sorted.bam -i sample1_sorted.bam
Number of references: 1
Reference Name: NC_045512.2
Reference Length: 29870
Using Region: NC_045512.2
Sorted By Coordinate
Sorted By Query Name`

While I never figured out what was going on, it ran just fine on a RHEL OS. I don't know if that helps, but I thought I'd share the information.

**Comment by gkarthik** [comment]
@ptskidmore @demiglidden This is weird behavior. Could you please provide a test file that I can use to reproduce this behavior ? Thanks!

**Comment by amagge** [comment]
Facing the same issue on Mac but the same command works on Ubuntu. 

```
% ivar trim -i X-177.sorted.bam -b swift_primers.bed -p X-177.trimmed                     
Number of references: 1
Reference Name: NC_045512
Reference Length: 29903
Using Region: NC_045512
Sorted By Coordinate
Sorted By Query Name
^C

```
I'm currently using ivar v1.3.1 on working on COVID files. 
The files are pretty large but I'm happy to provide more information.

**Comment by amagge** [comment]
Please ignore my earlier comment. I realized that the version that was actually being used by my shell was 1.0 and not 1.3.1. 
Installing iVar using brew on Mac installed v1.3 and fixed the issue. Installing iVar on Mac using conda installed v1.0 which actually causes the issue. However, installing iVar on Ubuntu using conda installed v1.3.1.
