### ISSUE TITLE
iVar output duplicated lines if a GFF file is supplied 

### ISSUE THREAD

**Issue by gianfilippo** [andersen-lab/ivar#99]
Hi,

I am running iVar as follow 
samtools mpileup -A -d 0 -Q 0 $BAM | ivar variants -p $variants -q 20 -t 0.1 -r $FASTA -g $GFF

**Describe the bug**
The resulting .TSV files shows duplicated lines for some of the variants called

**To Reproduce**
RUN
samtools mpileup -A -d 0 -Q 0 $BAM | ivar variants -p $variants -q 20 -t 0.1 -r $FASTA -g $GFF
VS
samtools mpileup -A -d 0 -Q 0 $BAM | ivar variants -p $variants -q 20 -t 0.1 -r $FASTA 

**Expected behavior**
No difference in the output files beyond amino acid translation

**Comment by ksw9** [comment]
Thanks team again for a great tool! I found a similar issue with duplicate entries in the .tsv.

**Comment by gkarthik** [comment]
The duplicate lines account occur if the nucleotide is present in more than 1 ORF in the GFF file. I wasn't able to figure out an easier way to show the translation for multiple ORFs.

**Comment by ksw9** [comment]
Right, that makes sense, thank you!

**Comment by gianfilippo** [comment]
Thanks
